/**
 * Seed danh muc khoa lam sang, ban kham va giuong noi bo tu file Excel nguon.
 * Nguon: C:\\Users\\admin\\Downloads\\Sa Dec Danh muc\\DM cổng\\FileKhoaPhongGiuong.xlsx
 * Cap nhat: 2026-06-16
 */

export const PHIEN_BAN_DANH_MUC_KHOA_LS_M01 = '2026-06-16-m01-seed-10';

export const COT_DANH_MUC_KHOA_LS_M01 = [
  "STT",
  "MA_KHOA",
  "TEN_KHOA",
  "BAN_KHAM",
  "GIUONG_PD",
  "GIUONG_TK",
  "GIUONG_HSTC",
  "GIUONG_HSCC",
  "TU_NGAY",
  "DEN_NGAY",
  "MA_CSKCB",
  "ID",
  "MA_LOAI_KCB",
  "LDLK",
  "LIEN_KHOA",
  "GIUONG_2015"
];

export const DANH_MUC_KHOA_LS_M01 = [
  {
    "STT": 1,
    "MA_KHOA": "K2718",
    "TEN_KHOA": "Khoa Phụ Sản - Nhi",
    "BAN_KHAM": "",
    "GIUONG_PD": 34,
    "GIUONG_TK": 34,
    "GIUONG_HSTC": "",
    "GIUONG_HSCC": "",
    "TU_NGAY": "",
    "DEN_NGAY": "",
    "MA_CSKCB": "87189",
    "ID": 427117,
    "MA_LOAI_KCB": 4,
    "LDLK": 2,
    "LIEN_KHOA": "",
    "GIUONG_2015": ""
  },
  {
    "STT": 2,
    "MA_KHOA": "K0313",
    "TEN_KHOA": "Khoa Nội - Da Liễu",
    "BAN_KHAM": "",
    "GIUONG_PD": 7,
    "GIUONG_TK": 7,
    "GIUONG_HSTC": "",
    "GIUONG_HSCC": "",
    "TU_NGAY": "",
    "DEN_NGAY": "",
    "MA_CSKCB": "87189",
    "ID": 427132,
    "MA_LOAI_KCB": 4,
    "LDLK": 2,
    "LIEN_KHOA": "",
    "GIUONG_2015": ""
  },
  {
    "STT": 3,
    "MA_KHOA": "K1926",
    "TEN_KHOA": "Khoa Ngoại - Gây mê hồi sức",
    "BAN_KHAM": "",
    "GIUONG_PD": 9,
    "GIUONG_TK": 9,
    "GIUONG_HSTC": "",
    "GIUONG_HSCC": "",
    "TU_NGAY": "",
    "DEN_NGAY": "",
    "MA_CSKCB": "87189",
    "ID": 427133,
    "MA_LOAI_KCB": 4,
    "LDLK": 2,
    "LIEN_KHOA": "",
    "GIUONG_2015": ""
  },
  {
    "STT": 4,
    "MA_KHOA": "03.18",
    "TEN_KHOA": "Nhi",
    "BAN_KHAM": 2,
    "GIUONG_PD": "",
    "GIUONG_TK": "",
    "GIUONG_HSTC": "",
    "GIUONG_HSCC": "",
    "TU_NGAY": "",
    "DEN_NGAY": "",
    "MA_CSKCB": "87189",
    "ID": 437242,
    "MA_LOAI_KCB": 1,
    "LDLK": 2,
    "LIEN_KHOA": "",
    "GIUONG_2015": ""
  },
  {
    "STT": 5,
    "MA_KHOA": "15.28",
    "TEN_KHOA": "Tai - Mũi - Họng",
    "BAN_KHAM": 1,
    "GIUONG_PD": "",
    "GIUONG_TK": "",
    "GIUONG_HSTC": "",
    "GIUONG_HSCC": "",
    "TU_NGAY": "",
    "DEN_NGAY": "",
    "MA_CSKCB": "87189",
    "ID": 437243,
    "MA_LOAI_KCB": 1,
    "LDLK": 2,
    "LIEN_KHOA": "",
    "GIUONG_2015": ""
  },
  {
    "STT": 6,
    "MA_KHOA": "02.03",
    "TEN_KHOA": "Nội tổng hợp",
    "BAN_KHAM": 2,
    "GIUONG_PD": "",
    "GIUONG_TK": "",
    "GIUONG_HSTC": "",
    "GIUONG_HSCC": "",
    "TU_NGAY": "",
    "DEN_NGAY": "",
    "MA_CSKCB": "87189",
    "ID": 437261,
    "MA_LOAI_KCB": 1,
    "LDLK": 2,
    "LIEN_KHOA": "",
    "GIUONG_2015": ""
  },
  {
    "STT": 7,
    "MA_KHOA": "10.19",
    "TEN_KHOA": "Ngoại tổng hợp",
    "BAN_KHAM": 1,
    "GIUONG_PD": "",
    "GIUONG_TK": "",
    "GIUONG_HSTC": "",
    "GIUONG_HSCC": "",
    "TU_NGAY": "",
    "DEN_NGAY": "",
    "MA_CSKCB": "87189",
    "ID": 437262,
    "MA_LOAI_KCB": 1,
    "LDLK": 2,
    "LIEN_KHOA": "",
    "GIUONG_2015": ""
  },
  {
    "STT": 8,
    "MA_KHOA": "13.27",
    "TEN_KHOA": "Phụ sản",
    "BAN_KHAM": 1,
    "GIUONG_PD": "",
    "GIUONG_TK": "",
    "GIUONG_HSTC": "",
    "GIUONG_HSCC": "",
    "TU_NGAY": "",
    "DEN_NGAY": "",
    "MA_CSKCB": "87189",
    "ID": 437263,
    "MA_LOAI_KCB": 1,
    "LDLK": 2,
    "LIEN_KHOA": "",
    "GIUONG_2015": ""
  },
  {
    "STT": 9,
    "MA_KHOA": "K44",
    "TEN_KHOA": "Khoa Dược",
    "BAN_KHAM": "",
    "GIUONG_PD": "",
    "GIUONG_TK": "",
    "GIUONG_HSTC": "",
    "GIUONG_HSCC": "",
    "TU_NGAY": "",
    "DEN_NGAY": "",
    "MA_CSKCB": "87189",
    "ID": 472857,
    "MA_LOAI_KCB": "",
    "LDLK": 2,
    "LIEN_KHOA": "",
    "GIUONG_2015": ""
  },
  {
    "STT": 10,
    "MA_KHOA": "K3947",
    "TEN_KHOA": "Khoa Cận lâm sàng",
    "BAN_KHAM": "",
    "GIUONG_PD": "",
    "GIUONG_TK": "",
    "GIUONG_HSTC": "",
    "GIUONG_HSCC": "",
    "TU_NGAY": "",
    "DEN_NGAY": "",
    "MA_CSKCB": "87189",
    "ID": 472886,
    "MA_LOAI_KCB": "",
    "LDLK": 2,
    "LIEN_KHOA": "",
    "GIUONG_2015": ""
  }
];
